name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:  
    - name: Remote SSH Pusblish
       uses: nerd4ever/ssh-action@0.1.0
        with:
          host: ${{secrets.CS_VM_IP}}
          user: ${{secrets.CS_VM_USER}}
          pass: ${{secrets.CS_VM_PASS}}
          command: echo  ok >> /home/std111/status
