name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:  
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master 
      with:
        host: ${{secrets.CS_VM_IP}}
        username: ${{secrets.CS_VM_USER}}
        password: ${{secrets.CS_VM_PASS}}   
        port: 22
        script: |
          pm2 delete all
          cd /home/st111/string-calculator
          git pull
          npm install
          echo  ok >> /home/std111/status
          pm2 start node index.js
         
