name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:  
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 193.106.55.101
        username: st111
        password: 2024@cs@2024
        script: |
          pm2 delete all
          cd /home/st111/string-calculator
          git pull
          npm install
          echo  ok >> /home/std111/status
          pm2 start node index.js
